name = "SobolSampling"
uuid = "b7eee0a8-fe27-4bd0-9686-d68697d1aae2"
authors = ["Michael <michael.groom@sydney.edu.au>"]
version = "0.1.0"

[deps]
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJTuning = "03970b2e-30c4-11ea-3135-d1576263f10f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[compat]
MLJBase = "1.8"
MLJTuning = "0.8"
Random = "1.9, 1.10, 1.11"
Sobol = "1.5"
Test = "1.9, 1.10, 1.11"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
